# Generated by Django 3.0.9 on 2020-08-13 12:52

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlutterWavePaymentMethod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("silver.paymentmethod",),
        ),
    ]
