# Generated by Django 4.2 on 2023-04-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_flutterwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(blank=True, max_length=4, null=True)),
                ('to_currency_code', models.CharField(blank=True, max_length=4, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('rate_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
