# Generated by Django 4.2 on 2023-04-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0057_alter_billingdocumentbase_id_alter_billinglog_id_and_more'),
        ('silver_flutterwave', '0002_currencyconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('dinersclub', 'Diners Club'), ('discover', 'Discover'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('americanexpress', 'American Express'), ('eftposaustralia', 'Eftpos Australia'), ('unknown', 'Unknown')], max_length=255, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('cvc_check', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1_check', models.CharField(blank=True, max_length=255, null=True)),
                ('address_zip_check', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='silver.customer')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='silver_flutterwave.flutterwavepaymentmethod')),
            ],
        ),
    ]
