# Generated by Django 4.2 on 2023-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_flutterwave', '0003_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='card',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='address_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='address_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='address_zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='funding',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit'), ('prepaid', 'Prepaid'), ('unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
