# Generated by Django 4.2 on 2023-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_flutterwave', '0004_rename_name_card_display_name_card_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvc_check',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('unchecked', 'Unchecked')], max_length=255, null=True),
        ),
    ]
