# Generated by Django 4.2 on 2023-04-26 12:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('silver_flutterwave', '0005_alter_card_cvc_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
