# Generated by Django 4.2 on 2023-04-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver_flutterwave', '0007_customer_remove_card_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='silver_flutterwave.customer'),
        ),
    ]
