# Generated by Django 4.2 on 2023-07-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("silver_flutterwave", "0011_card_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="state",
            field=models.CharField(
                blank=True, default="active", max_length=255, null=True
            ),
        ),
    ]
