# Generated by Django 4.2 on 2023-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("silver_flutterwave", "0012_alter_card_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="state",
        ),
        migrations.AddField(
            model_name="card",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="card",
            name="declined_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="declined_codes_counters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
