# Generated by Django 4.2 on 2023-07-10 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "silver_flutterwave",
            "0013_remove_card_state_card_active_card_declined_code_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="declined_code",
            new_name="decline_code",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="declined_codes_counters",
            new_name="decline_codes_counters",
        ),
    ]
